### ISSUE TITLE
View files are missing 

### ISSUE THREAD

**Issue by eboominathan** [patelmayankce/XeroPayroll-Codeigniter#1]
I download your files check to integerate the xero API with my rest api i cant found view files in your folders and also i dont know how to get the certs folder contents can you tel me anything about it

**Comment by patelmayankce** [comment]
you can get some idea regarding certs from 
http://www.linuxfromscratch.org/blfs/view/svn/postlfs/cacerts.html

and for view i have added some of the view i didn't tested yet...but you can get some idea from it...

**Comment by eboominathan** [comment]
thank you i will try!do you have any sample for integeration in codeigniter for xero
